import { useEffect, useMemo, useState } from 'react';
import { Download, FileSignature, ListChecks, Pencil, RefreshCw, Save, Search, Tags, Users, X } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { supabase } from './lib/supabase';
import majesticLogo from '../majestic-logo.png';

const ANO=2027;
const SERIES=['Berçário','Infantil I','Infantil II','Infantil III','Infantil IV','Infantil V','1º ano','2º ano','3º ano','4º ano','5º ano'];
const TURNOS=['Manhã','Tarde','Integral','A definir'];
const clean=v=>String(v||'').trim();
const dataBR=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const fichaVazia={aluno_id:'',matricula_id:'',nome_completo:'',nome_social:'',nome_para_lista:'',codigo_aluno:'',data_nascimento:'',serie:'',turma:'',turno:'',sala:'',numero_chamada:'',modalidade:'Regular',responsavel_nome:'',responsavel_telefone:'',responsavel_email:'',observacao_pedagogica:''};

async function carregarLogo(){try{const r=await fetch(majesticLogo,{cache:'force-cache'});if(!r.ok)return null;const blob=await r.blob();return await new Promise(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>resolve(null);fr.readAsDataURL(blob)})}catch{return null}}
function rodape(doc,titulo){const pages=doc.internal.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(225);doc.line(14,284,196,284);doc.setFontSize(8);doc.setTextColor(95);doc.text(`Berçário e Creche Escola Majestic • ${titulo} • Página ${i} de ${pages}`,14,290)}}

export default function Alunos2027(){
 const [alunos,setAlunos]=useState([]),[erro,setErro]=useState(''),[aviso,setAviso]=useState(''),[carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false);
 const [busca,setBusca]=useState(''),[serie,setSerie]=useState(''),[turma,setTurma]=useState(''),[turno,setTurno]=useState('');
 const [editando,setEditando]=useState(null),[ficha,setFicha]=useState(fichaVazia);

 async function carregar(){setCarregando(true);setErro('');const {data,error}=await supabase.from('vw_lista_alunos_2027').select('*').order('responsavel_nome').order('aluno');if(error){setErro(error.message);setAlunos([])}else setAlunos(data||[]);setCarregando(false)}
 useEffect(()=>{carregar();const canal=supabase.channel('majestic-alunos-2027').on('postgres_changes',{event:'*',schema:'public',table:'alunos'},carregar).on('postgres_changes',{event:'*',schema:'public',table:'matriculas_academicas'},carregar).on('postgres_changes',{event:'*',schema:'public',table:'gestao_clientes'},carregar).subscribe();return()=>supabase.removeChannel(canal)},[]);

 const series=useMemo(()=>[...new Set([...SERIES,...alunos.map(a=>clean(a.serie)).filter(Boolean)])],[alunos]);
 const turmas=useMemo(()=>[...new Set(alunos.filter(a=>!serie||a.serie===serie).map(a=>clean(a.turma)).filter(Boolean))].sort(),[alunos,serie]);
 const turnos=useMemo(()=>[...new Set(alunos.filter(a=>(!serie||a.serie===serie)&&(!turma||a.turma===turma)).map(a=>clean(a.turno)).filter(Boolean))].sort(),[alunos,serie,turma]);
 const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return alunos.filter(a=>(!serie||a.serie===serie)&&(!turma||a.turma===turma)&&(!turno||a.turno===turno)&&(!q||`${a.codigo_familia||''} ${a.codigo_aluno||''} ${a.aluno||''} ${a.responsavel_nome||''} ${a.responsavel_telefone||''}`.toLowerCase().includes(q)))},[alunos,busca,serie,turma,turno]);
 const familias=useMemo(()=>{const mapa=new Map();filtrados.forEach(a=>{const k=a.codigo_familia||a.cliente_id||a.responsavel_nome||'sem-id';if(!mapa.has(k))mapa.set(k,{codigo_familia:a.codigo_familia||'—',responsavel:a.responsavel_nome||'—',telefone:a.responsavel_telefone||'—',alunos:[]});mapa.get(k).alunos.push(a)});return [...mapa.values()]},[filtrados]);
 const grupos=useMemo(()=>new Set(filtrados.map(a=>`${a.serie}|${a.turma||''}|${a.turno}`)).size,[filtrados]);

 function abrirEdicao(a){setEditando(a);setFicha({aluno_id:a.aluno_id||'',matricula_id:a.matricula_id||'',nome_completo:a.nome_completo||a.aluno||'',nome_social:a.nome_social||'',nome_para_lista:a.nome_lista||'',codigo_aluno:a.codigo_aluno||'',data_nascimento:a.data_nascimento?String(a.data_nascimento).slice(0,10):'',serie:a.serie||'',turma:a.turma||'',turno:a.turno||'',sala:a.sala||'',numero_chamada:a.numero_chamada??'',modalidade:a.modalidade||'Regular',responsavel_nome:a.responsavel_nome||'',responsavel_telefone:a.responsavel_telefone||'',responsavel_email:a.responsavel_email||'',observacao_pedagogica:a.observacao_pedagogica||''});setAviso('');window.scrollTo({top:0,behavior:'smooth'})}
 function fecharEdicao(){setEditando(null);setFicha(fichaVazia)}
 function campo(k,v){setFicha(f=>({...f,[k]:v}))}

 async function salvarEdicao(e){e.preventDefault();if(!ficha.aluno_id||!ficha.matricula_id||!ficha.nome_completo.trim()||!ficha.serie||!ficha.turno){setAviso('Preencha nome do aluno, série e turno.');return}setSalvando(true);setAviso('Salvando organização acadêmica...');const alunoPayload={nome_completo:ficha.nome_completo.trim(),nome_social:ficha.nome_social.trim()||null,codigo_aluno:ficha.codigo_aluno.trim()||null,data_nascimento:ficha.data_nascimento||null,atualizado_em:new Date().toISOString()};const matriculaPayload={serie:ficha.serie,turma:ficha.turma.trim()||null,turno:ficha.turno,sala:ficha.sala.trim()||null,numero_chamada:ficha.numero_chamada===''?null:Number(ficha.numero_chamada),nome_para_lista:ficha.nome_para_lista.trim()||null,modalidade:ficha.modalidade||'Regular',responsavel_nome:ficha.responsavel_nome.trim()||null,responsavel_telefone:ficha.responsavel_telefone.trim()||null,responsavel_email:ficha.responsavel_email.trim()||null,observacao_pedagogica:ficha.observacao_pedagogica.trim()||null,atualizado_em:new Date().toISOString()};const [ra,rm]=await Promise.all([supabase.from('alunos').update(alunoPayload).eq('id',ficha.aluno_id),supabase.from('matriculas_academicas').update(matriculaPayload).eq('id',ficha.matricula_id)]);setSalvando(false);if(ra.error||rm.error){setAviso((ra.error||rm.error).message);return}setAviso(`Aluno ${ficha.nome_completo} atualizado.`);fecharEdicao();await carregar()}

 async function gerar(tipo){if(!filtrados.length)return;const logo=await carregarLogo(),doc=new jsPDF({unit:'mm',format:'a4'}),titulo=tipo==='chamada'?'LISTA DE CHAMADA':tipo==='assinatura'?'LISTA DE ASSINATURA':'LISTA DE ALUNOS';if(logo){try{doc.addImage(logo,'PNG',14,8,50,22,undefined,'FAST')}catch{}}doc.setFont('helvetica','bold');doc.setFontSize(17);doc.setTextColor(16,42,86);doc.text(`${titulo} • ${ANO}`,logo?72:14,16);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(70);doc.text(`Série: ${serie||'Todas'} • Turma: ${turma||'Todas'} • Turno: ${turno||'Todos'}`,logo?72:14,23);doc.text(`${filtrados.length} aluno(s) • ${familias.length} família(s) • Emitido em ${new Date().toLocaleString('pt-BR')}`,logo?72:14,29);let head,body;if(tipo==='chamada'){head=[['Nº','ID Aluno','Aluno','1','2','3','4','5','6','7','8','9','10']];body=filtrados.map((a,i)=>[a.numero_chamada||i+1,a.codigo_aluno||'—',a.nome_lista||a.aluno,'','','','','','','','','',''])}else if(tipo==='assinatura'){head=[['ID Família','Responsável','ID Aluno','Aluno','Assinatura']];body=filtrados.map(a=>[a.codigo_familia||'—',a.responsavel_nome||'',a.codigo_aluno||'—',a.nome_lista||a.aluno,''])}else{head=[['ID Família','Responsável','ID Aluno','Aluno','Série','Turma','Turno','Telefone']];body=filtrados.map(a=>[a.codigo_familia||'—',a.responsavel_nome||'',a.codigo_aluno||'—',a.nome_lista||a.aluno,a.serie||'',a.turma||'',a.turno||'',a.responsavel_telefone||''])}autoTable(doc,{startY:37,head,body,theme:'grid',styles:{fontSize:tipo==='chamada'?6:6.7,cellPadding:1.6,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]},columnStyles:tipo==='assinatura'?{4:{cellWidth:48}}:{}});rodape(doc,titulo);doc.save(`majestic-${tipo}-${ANO}.pdf`)}

 return <section className="modulePage">
  <section className="panel" style={{padding:24}}>
   <div className="panelHead" style={{alignItems:'flex-start',gap:14}}><div><p className="eyebrow">BASE ACADÊMICA • {ANO}</p><h3 style={{fontSize:24,margin:'4px 0'}}>Famílias e Alunos 2027</h3><p>Organização por ID da família, responsável e aluno, com vínculo acadêmico por série, turma e turno.</p></div><button className="icon" type="button" onClick={carregar}><RefreshCw size={18}/></button></div>
   {erro&&<div className="alerta" style={{marginTop:12}}>Base acadêmica: {erro}</div>}{aviso&&<div className="alerta" style={{marginTop:12}}>{aviso}</div>}
   {editando&&<form onSubmit={salvarEdicao} style={{marginTop:18,padding:18,border:'1px solid #cddcf0',borderRadius:16,background:'#f8fbff'}}><div style={{display:'flex',justifyContent:'space-between',gap:14}}><div><p className="eyebrow">ORGANIZAÇÃO ACADÊMICA</p><h3>Editar aluno / organizar turma</h3></div><button type="button" className="icon" onClick={fecharEdicao}><X size={18}/></button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}><label>Nome completo *<input required value={ficha.nome_completo} onChange={e=>campo('nome_completo',e.target.value)}/></label><label>Nome para lista<input value={ficha.nome_para_lista} onChange={e=>campo('nome_para_lista',e.target.value)}/></label><label>ID do aluno<input value={ficha.codigo_aluno} onChange={e=>campo('codigo_aluno',e.target.value)}/></label><label>Data de nascimento<input type="date" value={ficha.data_nascimento} onChange={e=>campo('data_nascimento',e.target.value)}/></label><label>Série *<select required value={ficha.serie} onChange={e=>campo('serie',e.target.value)}><option value="">Selecione</option>{series.map(x=><option key={x}>{x}</option>)}</select></label><label>Turma<input value={ficha.turma} onChange={e=>campo('turma',e.target.value.toUpperCase())}/></label><label>Turno *<select required value={ficha.turno} onChange={e=>campo('turno',e.target.value)}><option value="">Selecione</option>{TURNOS.map(x=><option key={x}>{x}</option>)}</select></label><label>Sala<input value={ficha.sala} onChange={e=>campo('sala',e.target.value)}/></label><label>Nº da chamada<input type="number" min="1" value={ficha.numero_chamada} onChange={e=>campo('numero_chamada',e.target.value)}/></label><label>Responsável<input value={ficha.responsavel_nome} onChange={e=>campo('responsavel_nome',e.target.value)}/></label><label>Telefone<input value={ficha.responsavel_telefone} onChange={e=>campo('responsavel_telefone',e.target.value)}/></label><label>E-mail<input value={ficha.responsavel_email} onChange={e=>campo('responsavel_email',e.target.value)}/></label><label style={{gridColumn:'1/-1'}}>Observação pedagógica<textarea rows="3" value={ficha.observacao_pedagogica} onChange={e=>campo('observacao_pedagogica',e.target.value)}/></label></div><div style={{display:'flex',gap:10,marginTop:16}}><button className="primary" type="submit" disabled={salvando}><Save size={17}/>{salvando?'Salvando...':'Salvar organização'}</button><button type="button" onClick={fecharEdicao}>Cancelar</button></div></form>}

   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12,margin:'18px 0'}}><article style={{padding:16,border:'1px solid #e4ebf4',borderRadius:14}}><Users size={20}/><small style={{display:'block',marginTop:7}}>Famílias</small><strong style={{fontSize:27}}>{carregando?'...':familias.length}</strong></article><article style={{padding:16,border:'1px solid #e4ebf4',borderRadius:14}}><ListChecks size={20}/><small style={{display:'block',marginTop:7}}>Alunos matriculados</small><strong style={{fontSize:27}}>{filtrados.length}</strong></article><article style={{padding:16,border:'1px solid #e4ebf4',borderRadius:14}}><Tags size={20}/><small style={{display:'block',marginTop:7}}>Turmas / grupos</small><strong style={{fontSize:27}}>{grupos}</strong></article></div>
   <div style={{display:'grid',gridTemplateColumns:'2fr repeat(3,minmax(130px,1fr))',gap:10,alignItems:'end'}}><label>Buscar ID, responsável ou aluno<div className="crmSearch"><Search size={17}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="F2027..., A2027..., responsável ou aluno"/></div></label><label>Série<select value={serie} onChange={e=>{setSerie(e.target.value);setTurma('');setTurno('')}}><option value="">Todas</option>{series.map(x=><option key={x}>{x}</option>)}</select></label><label>Turma<select value={turma} onChange={e=>{setTurma(e.target.value);setTurno('')}}><option value="">Todas</option>{turmas.map(x=><option key={x}>{x}</option>)}</select></label><label>Turno<select value={turno} onChange={e=>setTurno(e.target.value)}><option value="">Todos</option>{turnos.map(x=><option key={x}>{x}</option>)}</select></label></div>
   <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}><button className="primary" type="button" onClick={()=>gerar('lista')}><Download size={17}/>Lista de alunos</button><button className="primary" type="button" onClick={()=>gerar('chamada')}><ListChecks size={17}/>Lista de chamada</button><button className="primary" type="button" onClick={()=>gerar('assinatura')}><FileSignature size={17}/>Lista de assinatura</button></div>
  </section>

  <section className="panel" style={{marginTop:16,padding:20,overflowX:'auto'}}><div className="panelHead"><div><h3>Famílias / responsáveis</h3><p>{familias.length} família(s) no filtro atual.</p></div></div><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr>{['ID Família','Responsável','Telefone','Qtd. alunos','Alunos vinculados'].map(h=><th key={h} style={{textAlign:'left',padding:'10px 8px',borderBottom:'1px solid #dbe4ef'}}>{h}</th>)}</tr></thead><tbody>{familias.map((f,i)=><tr key={`${f.codigo_familia}-${i}`}><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}><strong>{f.codigo_familia}</strong></td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{f.responsavel}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{f.telefone}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{f.alunos.length}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{f.alunos.map(a=>`${a.codigo_aluno||'—'} · ${a.aluno}`).join(' | ')}</td></tr>)}</tbody></table></section>

  <section className="panel" style={{marginTop:16,padding:20,overflowX:'auto'}}><div className="panelHead"><div><h3>Alunos matriculados</h3><p>{filtrados.length} aluno(s) no filtro atual.</p></div></div><table style={{width:'100%',borderCollapse:'collapse',minWidth:1280}}><thead><tr>{['ID Família','Responsável','ID Aluno','Aluno','Nascimento','Série','Turma','Sala','Turno','Nº chamada','Atendente','Ação'].map(h=><th key={h} style={{textAlign:'left',padding:'10px 8px',borderBottom:'1px solid #dbe4ef'}}>{h}</th>)}</tr></thead><tbody>{filtrados.map((a,i)=><tr key={a.matricula_id||i}><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.codigo_familia||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.responsavel_nome||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}><strong>{a.codigo_aluno||'—'}</strong></td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}><strong>{a.nome_lista||a.aluno}</strong></td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{dataBR(a.data_nascimento)}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.serie}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.turma||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.sala||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.turno}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.numero_chamada||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}>{a.atendente_nome||'—'}</td><td style={{padding:8,borderBottom:'1px solid #edf1f6'}}><button type="button" onClick={()=>abrirEdicao(a)} style={{display:'inline-flex',alignItems:'center',gap:6,border:'1px solid #cfd9e8',borderRadius:9,padding:'8px 10px',background:'#fff',cursor:'pointer',fontWeight:700}}><Pencil size={15}/>Editar</button></td></tr>)}{!filtrados.length&&<tr><td colSpan="12" style={{padding:24,textAlign:'center'}}>Nenhum aluno encontrado.</td></tr>}</tbody></table></section>
 </section>
}
