import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, Download, FileText, PlayCircle, RotateCcw, Search, UserCheck, Users } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { supabase } from './lib/supabase';
import { carregarCatalogoOficial, fallbackCatalogo } from './lib/comercialOficial';
import { gerarPropostaComercialPDF } from './lib/propostaComercialPdf';
import majesticLogo from '../majestic-logo.png';

const ETAPAS=['contato','perfil','interesse','visita','proposta','decisao','matriculado'];
const LABELS={contato:'Contato',perfil:'Perfil identificado',interesse:'Interesse',visita:'Visita',proposta:'Proposta',decisao:'Decisão',matriculado:'Matrícula',perdido:'Não converteu'};
const SERIES=['Berçário','Infantil I','Infantil II','Infantil III','Infantil IV','Infantil V','1º ano','2º ano','3º ano','4º ano','5º ano'];
const TURNOS=['Manhã','Tarde','Integral','A definir'];
const ORIGENS=['WhatsApp','Telefone','Presencial','Instagram','Indicação','Google','Site','Outro'];
const agora=()=>new Date().toISOString();
const fmt=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const dataBr=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const simNao=v=>v?'Sim':'Não';
const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const vazio={nome_responsavel:'',nome_aluno:'',telefone:'',email:'',data_nascimento:'',idade:'',cep:'',logradouro:'',numero:'',complemento:'',bairro:'',cidade:'Fortaleza',uf:'CE',ponto_referencia:'',escola_atual:'',possui_laudo:false,observacao_laudo:'',serie:'',turno_preferencia:'',modalidade:'Regular',tipo_aluno:'novato',origem:'',interesse_principal:'',proximo_contato_at:'',motivo_perda:''};

async function carregarLogo(){
 try{const r=await fetch(majesticLogo,{cache:'force-cache'});if(!r.ok)return null;const blob=await r.blob();return await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>resolve(null);reader.readAsDataURL(blob)})}catch{return null}
}
function aplicarRodape(doc){const pages=doc.internal.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setDrawColor(225);doc.line(14,285,196,285);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(90);doc.text(`Berçário e Creche Escola Majestic • Gestão 2027 • Página ${i} de ${pages}`,14,290)}}
function resumoOrigensPeriodo(dados,clientes){const mapa={};dados.forEach(a=>{const c=clientes.find(x=>x.id===a.cliente_id)||{};const origem=c.origem||'Não informado';mapa[origem]=(mapa[origem]||0)+1});const total=Math.max(dados.length,1);return Object.entries(mapa).sort((a,b)=>b[1]-a[1]).map(([origem,qtd])=>[origem,qtd,`${(qtd/total*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`])}
function enderecoCompleto(c={}){return [c.logradouro,c.numero&&`nº ${c.numero}`,c.complemento,c.bairro,c.cidade,c.uf,c.cep&&`CEP ${c.cep}`].filter(Boolean).join(', ')||'Não informado'}
function aplicavelSerie(item,serie){if(!serie)return false;if(Array.isArray(item.serieAplicavel)&&item.serieAplicavel.length)return item.serieAplicavel.includes(serie);const id=item.id||'',cat=item.categoria||'';const infantil=serie.startsWith('Infantil');const fundamental=/^[1-5]º ano$/.test(serie);if(serie==='Berçário')return ['Berçário','Alimentação','Day Care'].includes(cat)||id==='blocos-atividades'||id==='plano-utilizacao'||id==='farda-sti';if(serie==='Infantil I')return id.startsWith('inf1-')||['Tempo Integral','Alimentação','Day Care','Esportes'].includes(cat)||id==='farda-educacao-infantil'||id==='blocos-atividades'||id==='plano-utilizacao';if(infantil)return id.startsWith('inf2-5-')||['Tempo Integral','Alimentação','Day Care','Esportes'].includes(cat)||id==='farda-educacao-infantil'||id==='plano-utilizacao';if(fundamental)return id.startsWith('inf2-5-')||['Tempo Integral','Alimentação','Day Care','Esportes'].includes(cat)||['farda-fundamental','farda-educacao-fisica','plano-utilizacao'].includes(id);return false}
function etapaAutomatica(f,acoes={}){if(acoes.matriculado)return {etapa:'matriculado',pct:100};if(acoes.perdido)return {etapa:'perdido',pct:100};if(acoes.confirmou)return {etapa:'decisao',pct:88};if(acoes.proposta)return {etapa:'proposta',pct:72};if(acoes.visita)return {etapa:'visita',pct:58};if(f.interesse_principal)return {etapa:'interesse',pct:43};if(f.nome_aluno&&f.serie&&f.turno_preferencia)return {etapa:'perfil',pct:28};return {etapa:'contato',pct:12}}

export default function AtendimentoCRM({profile}){
 const funcionario=profile?.nome||'';
 const [clientes,setClientes]=useState([]),[atendimentos,setAtendimentos]=useState([]),[busca,setBusca]=useState(''),[selecionado,setSelecionado]=useState(null),[atual,setAtual]=useState(null),[aviso,setAviso]=useState('');
 const [atendentes,setAtendentes]=useState([]),[atendenteSelecionado,setAtendenteSelecionado]=useState('');
 const [form,setForm]=useState(vazio),[obs,setObs]=useState(''),[acoes,setAcoes]=useState({visita:false,proposta:false,confirmou:false,matriculado:false,perdido:false}),[dataInicio,setDataInicio]=useState(()=>new Date().toISOString().slice(0,10)),[dataFim,setDataFim]=useState(()=>new Date().toISOString().slice(0,10));
 const [itensSelecionados,setItensSelecionados]=useState([]),[estadoSalvar,setEstadoSalvar]=useState('idle'),[comercial,setComercial]=useState(()=>fallbackCatalogo());
 const itensSerie=useMemo(()=>comercial.filter(i=>aplicavelSerie(i,form.serie)),[comercial,form.serie]);
 const itensOrcamento=useMemo(()=>itensSerie.filter(i=>itensSelecionados.includes(i.id)),[itensSerie,itensSelecionados]);
 const totalOrcamento=useMemo(()=>itensOrcamento.reduce((s,i)=>s+Number(i.valor2027??i.valor2026??0),0),[itensOrcamento]);
 const atendenteAtual=useMemo(()=>atendentes.find(a=>String(a.id)===String(atendenteSelecionado))||null,[atendentes,atendenteSelecionado]);
 const auto=etapaAutomatica(form,acoes);

 useEffect(()=>{carregar();carregarComercial();carregarAtendentes();const canal=supabase.channel('crm-equipe-sync-v9').on('postgres_changes',{event:'*',schema:'public',table:'gestao_clientes'},carregar).on('postgres_changes',{event:'*',schema:'public',table:'gestao_atendimentos'},carregar).on('postgres_changes',{event:'*',schema:'public',table:'produtos_comerciais'},carregarComercial).on('postgres_changes',{event:'*',schema:'public',table:'atendentes'},carregarAtendentes).subscribe();return()=>supabase.removeChannel(canal)},[]);
 async function carregar(){const [c,a]=await Promise.all([supabase.from('gestao_clientes').select('*').order('updated_at',{ascending:false}).limit(1500),supabase.from('gestao_atendimentos').select('*').order('iniciado_at',{ascending:false}).limit(3000)]);if(c.error||a.error){setAviso(`Sincronização: ${(c.error||a.error)?.message}`);return}setClientes(c.data||[]);setAtendimentos(a.data||[])}
 async function carregarComercial(){try{setComercial(await carregarCatalogoOficial())}catch{setComercial(fallbackCatalogo())}}
 async function carregarAtendentes(){const {data,error}=await supabase.from('atendentes').select('*').order('ordem',{ascending:true}).order('nome',{ascending:true});if(error){setAviso(`Atendentes: ${error.message}`);return}setAtendentes(data||[])}
 const resultados=useMemo(()=>{const q=busca.trim().toLowerCase();if(q.length<2)return[];return clientes.filter(c=>`${c.nome_responsavel||''} ${c.nome_aluno||''} ${c.telefone||''} ${c.email||''}`.toLowerCase().includes(q)).slice(0,8)},[clientes,busca]);
 const historico=useMemo(()=>selecionado?atendimentos.filter(a=>a.cliente_id===selecionado.id):[],[atendimentos,selecionado]);
 const meusHoje=useMemo(()=>{const hoje=new Date().toISOString().slice(0,10);return atendimentos.filter(a=>String(a.iniciado_at||'').slice(0,10)===hoje)},[atendimentos]);
 const atendimentosPeriodo=useMemo(()=>{const ini=new Date(`${dataInicio}T00:00:00`),fim=new Date(`${dataFim}T23:59:59`);return atendimentos.filter(a=>{const d=new Date(a.iniciado_at);return d>=ini&&d<=fim})},[atendimentos,dataInicio,dataFim]);
 const matriculas=clientes.filter(c=>c.matriculado).length,conversao=clientes.length?matriculas/clientes.length*100:0;

 function novo(){setSelecionado(null);setAtual(null);setAtendenteSelecionado('');setBusca('');setForm(vazio);setObs('');setItensSelecionados([]);setEstadoSalvar('idle');setAcoes({visita:false,proposta:false,confirmou:false,matriculado:false,perdido:false})}
 function escolher(c){setSelecionado(c);setForm({...vazio,...c,data_nascimento:c.data_nascimento||'',proximo_contato_at:c.proximo_contato_at?String(c.proximo_contato_at).slice(0,16):''});setBusca('');const u=atendimentos.find(a=>a.cliente_id===c.id);setAtual(u||null);setAtendenteSelecionado(u?.atendente_id?String(u.atendente_id):'');setItensSelecionados(Array.isArray(u?.orcamento_json)?u.orcamento_json.map(x=>x.id):[]);setObs(u?.observacao_fechamento||u?.observacao_abertura||'');setEstadoSalvar('idle');setAcoes({visita:!!u?.visita_realizada||['visita','proposta','decisao','matriculado'].includes(c.status_funil),proposta:!!u?.proposta_apresentada||['proposta','decisao','matriculado'].includes(c.status_funil),confirmou:!!u?.familia_confirmou_interesse||['decisao','matriculado'].includes(c.status_funil),matriculado:!!c.matriculado,perdido:c.status_funil==='perdido'})}
 function idadeNascimento(v){if(!v)return'';const d=new Date(v+'T12:00:00'),h=new Date();let i=h.getFullYear()-d.getFullYear();if(h<new Date(h.getFullYear(),d.getMonth(),d.getDate()))i--;return Math.max(0,i)}
 function campo(k,v){const novoForm={...form,[k]:v};if(k==='data_nascimento')novoForm.idade=idadeNascimento(v);if(k==='serie'&&v!==form.serie)setItensSelecionados([]);setForm(novoForm);setEstadoSalvar('idle')}
 function toggleItem(id){setItensSelecionados(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);setEstadoSalvar('idle')}
 function atualizarAcoes(novas){setAcoes(novas);setEstadoSalvar('idle')}

 async function iniciar(e){
  e.preventDefault();if(!profile?.id||!form.nome_responsavel.trim()||!form.nome_aluno.trim()||!form.origem||!atendenteSelecionado)return;
  const atendente=atendentes.find(a=>String(a.id)===String(atendenteSelecionado));if(!atendente||!atendente.ativo){setAviso('Selecione uma atendente ativa antes de iniciar.');return}
  setAviso('Sincronizando com a Direção...');setEstadoSalvar('saving');const status=etapaAutomatica(form,acoes);
  const payload={...form,idade:form.idade===''?null:Number(form.idade),data_nascimento:form.data_nascimento||null,proximo_contato_at:form.proximo_contato_at||null,status_funil:status.etapa==='perfil'?'contato':status.etapa,updated_at:agora()};let cli;
  if(selecionado){const r=await supabase.from('gestao_clientes').update(payload).eq('id',selecionado.id).select().single();if(r.error){setAviso(r.error.message);setEstadoSalvar('idle');return}cli=r.data}else{const r=await supabase.from('gestao_clientes').insert({...payload,matriculado:false}).select().single();if(r.error){setAviso(r.error.message);setEstadoSalvar('idle');return}cli=r.data}
  const orcamento=itensOrcamento.map(i=>({id:i.id,categoria:i.categoria,produto:i.produto,valor:Number(i.valor2027??i.valor2026??0),periodicidade:i.periodicidade||'',obrigatorio:!!i.obrigatorio,observacao:i.observacao||''}));
  const r=await supabase.from('gestao_atendimentos').insert({cliente_id:cli.id,funcionario_id:profile.id,funcionario_nome:funcionario,atendente_id:atendente.id,atendente_nome:atendente.nome,status:'em_andamento',etapa:status.etapa==='perfil'?'contato':status.etapa,progresso_percentual:status.pct,observacao_abertura:obs||'',proximo_contato_at:form.proximo_contato_at||null,orcamento_json:orcamento,valor_orcamento:totalOrcamento}).select().single();
  if(r.error){setAviso(r.error.message);setEstadoSalvar('idle');return}setSelecionado(cli);setAtual(r.data);setEstadoSalvar('sent');setAviso(`Atendimento iniciado por ${atendente.nome}. A Direção já consegue acompanhar.`);await carregar()
 }

 async function salvar(){
  if(!selecionado||estadoSalvar==='saving')return;setEstadoSalvar('saving');setAviso('Enviando atualização para a Gestão...');
  const st=etapaAutomatica(form,acoes),dbEtapa=st.etapa==='perfil'?'contato':st.etapa,final=['matriculado','perdido'].includes(st.etapa);
  const cliPayload={...form,idade:form.idade===''?null:Number(form.idade),data_nascimento:form.data_nascimento||null,proximo_contato_at:form.proximo_contato_at||null,status_funil:dbEtapa,matriculado:st.etapa==='matriculado',matriculado_at:st.etapa==='matriculado'?(selecionado.matriculado_at||agora()):selecionado.matriculado_at,updated_at:agora()};
  const c=await supabase.from('gestao_clientes').update(cliPayload).eq('id',selecionado.id).select().single();if(c.error){setAviso(c.error.message);setEstadoSalvar('idle');return}
  const orcamento=itensOrcamento.map(i=>({id:i.id,categoria:i.categoria,produto:i.produto,valor:Number(i.valor2027??i.valor2026??0),periodicidade:i.periodicidade||'',obrigatorio:!!i.obrigatorio,observacao:i.observacao||''}));
  const alvo=atual||atendimentos.find(a=>a.cliente_id===selecionado.id)||null;
  if(alvo){const a=await supabase.from('gestao_atendimentos').update({etapa:dbEtapa,progresso_percentual:st.pct,status:final?'concluido':'em_andamento',observacao_fechamento:obs||'',proximo_passo:form.proximo_contato_at?'Retornar contato':'',proximo_contato_at:form.proximo_contato_at||null,visita_realizada:acoes.visita,proposta_apresentada:acoes.proposta,familia_confirmou_interesse:acoes.confirmou,orcamento_json:orcamento,valor_orcamento:totalOrcamento,encerrado_at:final?(alvo.encerrado_at||agora()):null,updated_at:agora()}).eq('id',alvo.id).select().single();if(a.error){setAviso(a.error.message);setEstadoSalvar('idle');return}setAtual(a.data)}
  else if(atendenteSelecionado){const atendente=atendentes.find(a=>String(a.id)===String(atendenteSelecionado));const a=await supabase.from('gestao_atendimentos').insert({cliente_id:c.data.id,funcionario_id:profile?.id||null,funcionario_nome:funcionario,atendente_id:atendente?.id||null,atendente_nome:atendente?.nome||'',status:final?'concluido':'em_andamento',etapa:dbEtapa,progresso_percentual:st.pct,observacao_abertura:obs||'',observacao_fechamento:obs||'',proximo_contato_at:form.proximo_contato_at||null,visita_realizada:acoes.visita,proposta_apresentada:acoes.proposta,familia_confirmou_interesse:acoes.confirmou,orcamento_json:orcamento,valor_orcamento:totalOrcamento,encerrado_at:final?agora():null}).select().single();if(a.error){setAviso(a.error.message);setEstadoSalvar('idle');return}setAtual(a.data)}
  setSelecionado(c.data);setEstadoSalvar('sent');setAviso(final?'Atendimento concluído, salvo e enviado à Gestão. Você ainda pode editar e salvar novamente.':'Atendimento e orçamento enviados à Gestão. Você pode continuar editando e salvar novamente.');await carregar()
 }

 async function gerarPdfAtendimento(){try{const atendente=atual?.atendente_nome||atendenteAtual?.nome||atual?.funcionario_nome||funcionario;await gerarPropostaComercialPDF({form,itens:itensOrcamento,atendente,observacao:obs});setAviso('Proposta comercial gerada para a família.')}catch(e){setAviso(e?.message||'Não foi possível gerar a proposta comercial.')}}

 async function relatorio(){
  const dados=atendimentosPeriodo,logo=await carregarLogo(),doc=new jsPDF({unit:'mm',format:'a4'});const concluidos=dados.filter(a=>a.status==='concluido').length,abertos=dados.filter(a=>a.status==='em_andamento').length;const idsClientes=[...new Set(dados.map(a=>a.cliente_id).filter(Boolean))],clientesPeriodo=clientes.filter(c=>idsClientes.includes(c.id));const matsPeriodo=clientesPeriodo.filter(c=>c.matriculado).length,convPeriodo=clientesPeriodo.length?matsPeriodo/clientesPeriodo.length*100:0;
  if(logo){try{doc.addImage(logo,'PNG',14,8,55,24,undefined,'FAST')}catch{}}doc.setFont('helvetica','bold');doc.setFontSize(17);doc.setTextColor(16,42,86);doc.text('RELATÓRIO COMPLETO DE ATENDIMENTOS',logo?76:14,17);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(50,65,85);doc.text(`${dataInicio.split('-').reverse().join('/')} a ${dataFim.split('-').reverse().join('/')}`,logo?76:14,24);doc.text(`Gerado pelo acesso ${funcionario||'Gestão Majestic'} em ${new Date().toLocaleString('pt-BR')}`,logo?76:14,30);
  autoTable(doc,{startY:39,head:[['Indicador','Resultado']],body:[['Atendimentos no período',dados.length],['Em andamento',abertos],['Concluídos',concluidos],['Famílias únicas',clientesPeriodo.length],['Matrículas confirmadas',matsPeriodo],['Conversão do período',`${convPeriodo.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`]],headStyles:{fillColor:[16,42,86]}});
  let y=(doc.lastAutoTable?.finalY||80)+8;doc.setFont('helvetica','bold');doc.setTextColor(16,42,86);doc.text('Como as famílias conheceram a escola',14,y);autoTable(doc,{startY:y+3,head:[['Origem / canal','Atendimentos','Participação']],body:resumoOrigensPeriodo(dados,clientes),headStyles:{fillColor:[16,42,86]}});
  y=(doc.lastAutoTable?.finalY||y+20)+8;doc.setFont('helvetica','bold');doc.text('Resumo dos atendimentos',14,y);autoTable(doc,{startY:y+3,head:[['Data / hora','Aluno / responsável','Série / turno','Atendente','Etapa / status','Valor']],body:dados.map(a=>{const c=clientes.find(x=>x.id===a.cliente_id)||{};return [fmt(a.iniciado_at),`${c.nome_aluno||'-'}\n${c.nome_responsavel||'-'}`,`${c.serie||'-'}\n${c.turno_preferencia||'-'}`,a.atendente_nome||a.funcionario_nome||'-',`${LABELS[a.etapa]||a.etapa||'-'}\n${a.status==='concluido'?'Concluído':'Em andamento'}`,moeda(a.valor_orcamento)]}),styles:{fontSize:6.5,cellPadding:1.5,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]}});
  dados.forEach((a,idx)=>{const c=clientes.find(x=>x.id===a.cliente_id)||{};const itens=Array.isArray(a.orcamento_json)?a.orcamento_json:[];doc.addPage();if(logo){try{doc.addImage(logo,'PNG',14,8,45,20,undefined,'FAST')}catch{}}doc.setFont('helvetica','bold');doc.setFontSize(15);doc.setTextColor(16,42,86);doc.text(`ATENDIMENTO ${idx+1} • ${c.nome_aluno||'Aluno não informado'}`,65,17);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(`Registro: ${fmt(a.iniciado_at)} • Atualizado: ${fmt(a.updated_at)}`,65,24);
   autoTable(doc,{startY:34,head:[['DADOS DA FAMÍLIA / ALUNO','INFORMAÇÃO']],body:[['Aluno',c.nome_aluno||'—'],['Responsável',c.nome_responsavel||'—'],['Telefone / WhatsApp',c.telefone||'—'],['E-mail',c.email||'—'],['Nascimento',dataBr(c.data_nascimento)],['Idade',c.idade??'—'],['Tipo de aluno',c.tipo_aluno||'—'],['Endereço completo',enderecoCompleto(c)],['Ponto de referência',c.ponto_referencia||'—']],styles:{fontSize:8,cellPadding:1.6,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]}});
   autoTable(doc,{startY:(doc.lastAutoTable?.finalY||95)+5,head:[['PERFIL ESCOLAR / INTERESSE','INFORMAÇÃO']],body:[['Escola atual',c.escola_atual||'—'],['Série pretendida',c.serie||'—'],['Turno de preferência',c.turno_preferencia||'—'],['Modalidade',c.modalidade||'—'],['Como conheceu a escola',c.origem||'—'],['Principal interesse',c.interesse_principal||'—'],['Possui laudo / necessidade específica',simNao(c.possui_laudo)],['Observação sobre necessidade específica',c.observacao_laudo||'—']],styles:{fontSize:8,cellPadding:1.6,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]}});
   autoTable(doc,{startY:(doc.lastAutoTable?.finalY||145)+5,head:[['DADOS DO ATENDIMENTO','INFORMAÇÃO']],body:[['Atendente responsável',a.atendente_nome||a.funcionario_nome||'—'],['Acesso do sistema',a.funcionario_nome||'—'],['Etapa',LABELS[a.etapa]||a.etapa||'—'],['Status',a.status==='concluido'?'Concluído':'Em andamento'],['Progresso',`${a.progresso_percentual??0}%`],['Visita realizada',simNao(a.visita_realizada)],['Proposta apresentada',simNao(a.proposta_apresentada)],['Família confirmou interesse',simNao(a.familia_confirmou_interesse)],['Matrícula confirmada',simNao(c.matriculado)],['Próximo contato',fmt(a.proximo_contato_at||c.proximo_contato_at)],['Próximo passo',a.proximo_passo||'—'],['Motivo de perda',c.motivo_perda||'—'],['Observação de abertura',a.observacao_abertura||'—'],['Observação / fechamento',a.observacao_fechamento||'—'],['Encerrado em',fmt(a.encerrado_at)]],styles:{fontSize:7.6,cellPadding:1.4,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]}});
   if(itens.length){autoTable(doc,{startY:(doc.lastAutoTable?.finalY||205)+5,head:[['PRODUTO / SERVIÇO','CATEGORIA','PERIODICIDADE','VALOR','OBSERVAÇÃO']],body:itens.map(i=>[i.produto||'—',i.categoria||'—',i.periodicidade||'—',moeda(i.valor),`${i.obrigatorio?'Obrigatório. ':''}${i.observacao||''}`]),styles:{fontSize:6.8,cellPadding:1.3,overflow:'linebreak'},headStyles:{fillColor:[16,42,86]}});const yy=(doc.lastAutoTable?.finalY||240)+5;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(`Total do orçamento: ${moeda(a.valor_orcamento)}`,14,yy)}else{const yy=(doc.lastAutoTable?.finalY||205)+7;doc.setFont('helvetica','italic');doc.setFontSize(9);doc.text('Nenhum produto ou serviço foi registrado neste atendimento.',14,yy)}
  });
  aplicarRodape(doc);doc.save(`majestic-relatorio-completo-atendimentos-${dataInicio}-${dataFim}.pdf`)
 }

 const indice=Math.max(0,ETAPAS.indexOf(auto.etapa));const atendentesDisponiveis=atendentes.filter(a=>a.ativo||String(a.id)===String(atendenteSelecionado));
 return <section className="crmPage">
  <div className="crmHero"><div><span>ATENDIMENTO MAJESTIC</span><h2>Atender bem, registrar sem burocracia.</h2><p>Cadastre a família, o endereço completo, produtos apresentados e toda a evolução do atendimento em um único fluxo.</p></div><button type="button" onClick={novo}><RotateCcw size={17}/>Novo atendimento</button></div>
  {aviso&&<div className="crmNotice">{aviso}</div>}
  <div className="crmStats"><article><Users/><div><small>Atendimentos hoje</small><strong>{meusHoje.length}</strong></div></article><article><Clock3/><div><small>Em andamento</small><strong>{atendimentos.filter(a=>a.status==='em_andamento').length}</strong></div></article><article><UserCheck/><div><small>Matrículas</small><strong>{matriculas}</strong></div></article><article><CheckCircle2/><div><small>Conversão</small><strong>{conversao.toFixed(1)}%</strong></div></article></div>
  <section className="panel crmLookup"><div className="panelHead"><div><h3>Quem vamos atender?</h3><p>Busque antes de cadastrar. Um telefone, nome ou e-mail é suficiente.</p></div></div><div className="crmSearch"><Search size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Telefone, responsável, aluno ou e-mail"/></div>{resultados.length>0&&<div className="crmResults">{resultados.map(c=><button type="button" key={c.id} onClick={()=>escolher(c)}><strong>{c.nome_aluno}</strong><span>{c.nome_responsavel} • {c.telefone||c.email||'sem contato'} • {c.serie||'série não informada'}</span><em>{LABELS[c.status_funil]||'Cadastro'}</em></button>)}</div>}</section>
  <form className="panel crmForm" onSubmit={iniciar}><div className="crmFormTitle"><div><h3>{selecionado?'Continuar atendimento':'Dados da família e do aluno'}</h3><p>Agora o cadastro também guarda o endereço completo da família.</p></div><div className="crmAutoBadge">Etapa automática: <b>{LABELS[auto.etapa]}</b> • {auto.pct}%</div></div><div className="crmGrid">
   <label>Atendente responsável *<select required disabled={!!atual} value={atendenteSelecionado} onChange={e=>{setAtendenteSelecionado(e.target.value);setEstadoSalvar('idle')}}><option value="">Selecione quem está atendendo</option>{atendentesDisponiveis.map(a=><option key={a.id} value={a.id}>{a.nome}{a.ativo?'':' • desativada'}</option>)}</select></label><label>Acesso do sistema<input readOnly value={funcionario||profile?.email||'Gestão Majestic'}/></label><label>Como conheceu? *<select required value={form.origem} onChange={e=>campo('origem',e.target.value)}><option value="">Selecione</option>{ORIGENS.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Responsável *<input required value={form.nome_responsavel} onChange={e=>campo('nome_responsavel',e.target.value)}/></label><label>WhatsApp / telefone<input value={form.telefone} onChange={e=>campo('telefone',e.target.value)}/></label><label>E-mail<input value={form.email} onChange={e=>campo('email',e.target.value)}/></label>
   <label>Aluno *<input required value={form.nome_aluno} onChange={e=>campo('nome_aluno',e.target.value)}/></label><label>Data de nascimento<input type="date" value={form.data_nascimento} onChange={e=>campo('data_nascimento',e.target.value)}/></label><label>Idade<input type="number" min="0" max="30" value={form.idade} onChange={e=>campo('idade',e.target.value)}/></label>
   <label>CEP<input value={form.cep} onChange={e=>campo('cep',e.target.value)} placeholder="00000-000"/></label><label className="crmSpan2">Rua / Avenida / Logradouro<input value={form.logradouro} onChange={e=>campo('logradouro',e.target.value)} placeholder="Nome completo da rua ou avenida"/></label><label>Número<input value={form.numero} onChange={e=>campo('numero',e.target.value)} placeholder="Nº"/></label><label>Complemento<input value={form.complemento} onChange={e=>campo('complemento',e.target.value)} placeholder="Apto, bloco, casa..."/></label><label>Bairro<input value={form.bairro} onChange={e=>campo('bairro',e.target.value)}/></label><label>Cidade<input value={form.cidade} onChange={e=>campo('cidade',e.target.value)}/></label><label>UF<input maxLength="2" value={form.uf} onChange={e=>campo('uf',e.target.value.toUpperCase())}/></label><label className="crmSpan2">Ponto de referência<input value={form.ponto_referencia} onChange={e=>campo('ponto_referencia',e.target.value)} placeholder="Próximo a..."/></label>
   <label>Escola atual<input value={form.escola_atual} onChange={e=>campo('escola_atual',e.target.value)}/></label><label>Tipo<select value={form.tipo_aluno} onChange={e=>campo('tipo_aluno',e.target.value)}><option value="novato">Novato</option><option value="veterano">Veterano</option></select></label><label>Série pretendida<select value={form.serie} onChange={e=>campo('serie',e.target.value)}><option value="">Selecione</option>{SERIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Turno de preferência<select value={form.turno_preferencia} onChange={e=>campo('turno_preferencia',e.target.value)}><option value="">Selecione</option>{TURNOS.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Possui laudo / necessidade específica?<select value={form.possui_laudo?'sim':'nao'} onChange={e=>campo('possui_laudo',e.target.value==='sim')}><option value="nao">Não informado / Não</option><option value="sim">Sim</option></select></label>{form.possui_laudo&&<label className="crmSpan2">Observação necessária para o atendimento<input value={form.observacao_laudo} onChange={e=>campo('observacao_laudo',e.target.value)} placeholder="Registre somente o necessário para o atendimento escolar"/></label>}
   <label className="crmSpan2">Principal interesse da família<input value={form.interesse_principal} onChange={e=>campo('interesse_principal',e.target.value)} placeholder="Ex.: integral, proposta pedagógica, proximidade..."/></label><label>Próximo retorno<input type="datetime-local" value={form.proximo_contato_at} onChange={e=>campo('proximo_contato_at',e.target.value)}/></label><label className="crmWide">Anotação rápida<textarea rows="2" value={obs} onChange={e=>{setObs(e.target.value);setEstadoSalvar('idle')}} placeholder="O que é importante lembrar deste contato?"/></label>
  </div>
  {!atendentes.filter(a=>a.ativo).length&&<div className="crmNotice">Nenhuma atendente ativa foi cadastrada pela Direção. Cadastre pelo App da Direção antes de iniciar atendimentos.</div>}
  {form.serie&&<section className="crmBudget"><div className="crmBudgetHead"><div><span>ORÇAMENTO AUTOMÁTICO • FONTE OFICIAL SUPABASE</span><h3>Valores disponíveis para {form.serie}</h3><p>Marque somente os itens apresentados à família. Mudanças da Direção chegam em tempo real.</p></div><strong>{itensSelecionados.length} selecionado(s)</strong></div><div className="crmBudgetGrid">{itensSerie.map(i=><label key={i.id} className={itensSelecionados.includes(i.id)?'selected':''}><input type="checkbox" checked={itensSelecionados.includes(i.id)} onChange={()=>toggleItem(i.id)}/><div><small>{i.categoria} • {i.periodicidade||'avulso'}{i.obrigatorio?' • obrigatório':''}</small><b>{i.produto}</b><span>{i.observacao||''}</span></div><strong>{moeda(i.valor2027??i.valor2026)}</strong></label>)}</div><div className="crmBudgetTotal"><span>Itens selecionados para a proposta</span><strong>{itensSelecionados.length}</strong></div></section>}
  {!atual&&<button className="primary crmStart" type="submit" disabled={!atendenteSelecionado||estadoSalvar==='saving'}><PlayCircle size={18}/>{estadoSalvar==='saving'?'Enviando...':selecionado?'Retomar atendimento':'Iniciar e salvar atendimento'}</button>}</form>
  {(atual||selecionado)&&<section className="panel crmCurrent"><div className="crmCurrentHead"><div><span>DESEMPENHO DO ATENDIMENTO</span><h3>{form.nome_aluno}</h3><p>{atual?.atendente_nome||atendenteAtual?.nome||atual?.funcionario_nome||funcionario} • atualização automática conforme o atendimento evolui</p></div><strong>{auto.pct}% • {LABELS[auto.etapa]}</strong></div><div className="crmPerformance"><div className="crmPerformanceBar"><i style={{width:`${auto.pct}%`}}/></div><div className="crmSteps">{ETAPAS.map((e,i)=><div key={e} className={i<indice?'done':i===indice?'active':''}><i>{i+1}</i><span>{LABELS[e]}</span></div>)}</div></div><div className="crmQuickActions"><button type="button" className={acoes.visita?'done':''} onClick={()=>atualizarAcoes({...acoes,visita:!acoes.visita})}>✓ Visita realizada</button><button type="button" className={acoes.proposta?'done':''} onClick={()=>atualizarAcoes({...acoes,proposta:!acoes.proposta})}>✓ Proposta apresentada</button><button type="button" className={acoes.confirmou?'done':''} onClick={()=>atualizarAcoes({...acoes,confirmou:!acoes.confirmou})}>✓ Família confirmou interesse</button><button type="button" className="success" onClick={()=>atualizarAcoes({...acoes,matriculado:true,perdido:false})}>Matrícula confirmada</button><button type="button" className="loss" onClick={()=>atualizarAcoes({...acoes,perdido:true,matriculado:false})}>Não converteu</button></div>{acoes.perdido&&<label className="crmLossReason">Motivo<input value={form.motivo_perda} onChange={e=>campo('motivo_perda',e.target.value)} placeholder="Ex.: valor, localização, horário, concorrente..."/></label>}<div className="crmFinishActions"><button type="button" className="primary crmSave" onClick={salvar} disabled={estadoSalvar==='saving'} style={estadoSalvar==='sent'?{background:'#16a34a',borderColor:'#16a34a',color:'#fff'}:undefined}>{estadoSalvar==='saving'?'Enviando...':estadoSalvar==='sent'?<><CheckCircle2 size={17}/>Enviado à Gestão</>:'Salvar atendimento'}</button><button type="button" className="crmPdfBtn" onClick={gerarPdfAtendimento}><FileText size={17}/>Gerar proposta comercial PDF</button></div></section>}
  {selecionado&&historico.length>0&&<section className="panel crmHistory"><div className="panelHead"><div><h3>Linha do tempo da família</h3><p>Histórico recuperado automaticamente.</p></div></div>{historico.map(h=><article key={h.id}><div><strong>{LABELS[h.etapa]||h.etapa}</strong><small>{fmt(h.iniciado_at)} • {h.atendente_nome||h.funcionario_nome}</small></div><span>{h.status}</span><p>{h.observacao_fechamento||h.observacao_abertura||'Sem observação.'}</p></article>)}</section>}
  <section className="panel crmReport"><div><CalendarDays size={22}/><div><h3>Relatório completo do atendimento</h3><p>Além dos indicadores, o PDF agora traz uma ficha completa de cada pessoa: cadastro, endereço, escola, interesse, etapas, observações, produtos e valores.</p></div></div><label>Início<input type="date" value={dataInicio} onChange={e=>setDataInicio(e.target.value)}/></label><label>Fim<input type="date" value={dataFim} onChange={e=>setDataFim(e.target.value)}/></label><button type="button" className="primary" onClick={relatorio}><Download size={17}/>Baixar relatório completo</button></section>
  <section className="panel crmPeriodList"><div className="panelHead"><div><h3>{dataInicio===dataFim?'Atendimentos do dia':'Atendimentos do período'}</h3><p>{atendimentosPeriodo.length} atendimento(s) de {dataInicio.split('-').reverse().join('/')} a {dataFim.split('-').reverse().join('/')}.</p></div></div><div className="crmPeriodRows">{atendimentosPeriodo.map(a=>{const c=clientes.find(x=>x.id===a.cliente_id)||{};return <article key={a.id}><div><strong>{c.nome_aluno||'Aluno não informado'}</strong><span>{c.nome_responsavel||'Responsável não informado'} • {fmt(a.iniciado_at)}</span><small>{c.serie||'Sem série'} • {c.turno_preferencia||'Sem turno'} • {c.origem||'Origem não informada'} • {c.bairro||'Bairro não informado'}</small></div><div><b>{LABELS[a.etapa]||a.etapa}</b><span>{a.status==='concluido'?'Concluído':'Em andamento'}</span><small>{a.atendente_nome||a.funcionario_nome} • {c.telefone||'sem telefone'} • {moeda(a.valor_orcamento)}</small></div></article>})}{!atendimentosPeriodo.length&&<div className="empty">Nenhum atendimento encontrado nesse período.</div>}</div></section>
 </section>
}