import { useEffect, useMemo, useState } from 'react';
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { supabase } from './lib/supabase';

const SERIES=['Berçário','Infantil I','Infantil II','Infantil III','Infantil IV','Infantil V','1º ano','2º ano','3º ano','4º ano','5º ano'];
const num=v=>Number(String(v??'').replace(',','.'))||0;
const vazio={ordem:99,serie:'Infantil I',modalidade:'Regular',valor_base_2026:'',reajuste_percentual:'',plano_a_parcelas:12,plano_a_ate_vencimento:'',plano_a_apos_vencimento:'',plano_b_parcelas:13,plano_b_ate_vencimento:'',plano_b_apos_vencimento:'',observacao:'',ativo:true};

export default function FechamentoGeral2027(){
 const [linhas,setLinhas]=useState([]),[status,setStatus]=useState('Carregando fechamento geral...'),[salvando,setSalvando]=useState(false),[novo,setNovo]=useState(vazio);
 async function carregar(){const {data,error}=await supabase.from('fechamento_comercial_2027').select('*').eq('ativo',true).order('ordem').order('serie');if(error){setStatus(`Execute fechamento_geral_majestic_2027.sql • ${error.message}`);setLinhas([]);return}setLinhas(data||[]);setStatus('Fechamento Geral 2027 sincronizado com o Supabase')}
 useEffect(()=>{carregar();const c=supabase.channel('fechamento-geral-2027').on('postgres_changes',{event:'*',schema:'public',table:'fechamento_comercial_2027'},carregar).subscribe();return()=>supabase.removeChannel(c)},[]);
 const atualizar=(id,campo,valor)=>setLinhas(v=>v.map(x=>x.id===id?{...x,[campo]:valor}:x));
 const reajusteMedio=useMemo(()=>linhas.length?linhas.reduce((s,x)=>s+num(x.reajuste_percentual),0)/linhas.length:0,[linhas]);
 async function salvar(){setSalvando(true);setStatus('Salvando fechamento geral...');try{const payload=linhas.map(x=>({...x,valor_base_2026:num(x.valor_base_2026),reajuste_percentual:num(x.reajuste_percentual),plano_a_parcelas:Number(x.plano_a_parcelas||12),plano_a_ate_vencimento:num(x.plano_a_ate_vencimento),plano_a_apos_vencimento:num(x.plano_a_apos_vencimento),plano_b_parcelas:Number(x.plano_b_parcelas||13),plano_b_ate_vencimento:num(x.plano_b_ate_vencimento),plano_b_apos_vencimento:num(x.plano_b_apos_vencimento),observacao:x.observacao||null}));const {error}=await supabase.from('fechamento_comercial_2027').upsert(payload,{onConflict:'id'});if(error)throw error;setStatus('Fechamento Geral salvo.');await carregar()}catch(e){setStatus(`Erro ao salvar: ${e.message}`)}finally{setSalvando(false)}}
 async function adicionar(){const payload={...novo,valor_base_2026:num(novo.valor_base_2026),reajuste_percentual:num(novo.reajuste_percentual),plano_a_ate_vencimento:num(novo.plano_a_ate_vencimento),plano_a_apos_vencimento:num(novo.plano_a_apos_vencimento),plano_b_ate_vencimento:num(novo.plano_b_ate_vencimento),plano_b_apos_vencimento:num(novo.plano_b_apos_vencimento)};const {error}=await supabase.from('fechamento_comercial_2027').insert(payload);if(error){setStatus(`Erro ao adicionar: ${error.message}`);return}setNovo(vazio);await carregar()}
 async function remover(id){if(!confirm('Desativar esta linha do fechamento geral?'))return;await supabase.from('fechamento_comercial_2027').update({ativo:false}).eq('id',id);await carregar()}
 const inp=(x,c,w=92)=><input style={{width:w}} inputMode="decimal" value={x[c]??''} onChange={e=>atualizar(x.id,c,e.target.value)}/>;
 return <section className="panel commercialTable" style={{marginBottom:18}}>
  <div className="panelHead"><div><p className="eyebrow">FECHAMENTO GERAL • MATRÍCULAS 2027</p><h3>Mensalidades por série — modelo Cora Gestão</h3><p>Uma linha por série e modalidade. Plano A em 12x e Plano B em 13x, cada um com valor até e após o vencimento.</p></div><div style={{display:'flex',gap:8}}><button onClick={carregar}><RefreshCw size={16}/>Atualizar</button><button className="primary" onClick={salvar} disabled={salvando}><Save size={16}/>{salvando?'Salvando...':'Salvar fechamento'}</button></div></div>
  <div style={{display:'flex',gap:14,flexWrap:'wrap',margin:'10px 0 14px'}}><span><b>{linhas.length}</b> séries/modalidades</span><span>Reajuste médio: <b>{reajusteMedio.toFixed(2)}%</b></span><span>{status}</span></div>
  <div className="tableWrap"><table><thead><tr><th>Série</th><th>Modalidade</th><th>Base 2026</th><th>Reajuste %</th><th>Plano A</th><th>A • até venc.</th><th>A • após venc.</th><th>Plano B</th><th>B • até venc.</th><th>B • após venc.</th><th>Observação</th><th></th></tr></thead><tbody>{linhas.map(x=><tr key={x.id}><td><select value={x.serie} onChange={e=>atualizar(x.id,'serie',e.target.value)}>{SERIES.map(s=><option key={s}>{s}</option>)}</select></td><td><input style={{width:125}} value={x.modalidade||''} onChange={e=>atualizar(x.id,'modalidade',e.target.value)} placeholder="Regular / Integral..."/></td><td>{inp(x,'valor_base_2026')}</td><td>{inp(x,'reajuste_percentual',72)}</td><td><input style={{width:58}} type="number" min="1" value={x.plano_a_parcelas??12} onChange={e=>atualizar(x.id,'plano_a_parcelas',e.target.value)}/>x</td><td>{inp(x,'plano_a_ate_vencimento')}</td><td>{inp(x,'plano_a_apos_vencimento')}</td><td><input style={{width:58}} type="number" min="1" value={x.plano_b_parcelas??13} onChange={e=>atualizar(x.id,'plano_b_parcelas',e.target.value)}/>x</td><td>{inp(x,'plano_b_ate_vencimento')}</td><td>{inp(x,'plano_b_apos_vencimento')}</td><td><input style={{minWidth:150}} value={x.observacao||''} onChange={e=>atualizar(x.id,'observacao',e.target.value)}/></td><td><button className="dangerIcon" onClick={()=>remover(x.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>
  <div style={{marginTop:18,paddingTop:16,borderTop:'1px solid #e7edf5'}}><h4 style={{margin:'0 0 10px'}}>Adicionar série / modalidade</h4><div className="formGrid"><label>Série<select value={novo.serie} onChange={e=>setNovo({...novo,serie:e.target.value})}>{SERIES.map(s=><option key={s}>{s}</option>)}</select></label><label>Modalidade<input value={novo.modalidade} onChange={e=>setNovo({...novo,modalidade:e.target.value})}/></label><label>Base 2026<input value={novo.valor_base_2026} onChange={e=>setNovo({...novo,valor_base_2026:e.target.value})}/></label><label>Reajuste %<input value={novo.reajuste_percentual} onChange={e=>setNovo({...novo,reajuste_percentual:e.target.value})}/></label><label>Plano A parcelas<input type="number" value={novo.plano_a_parcelas} onChange={e=>setNovo({...novo,plano_a_parcelas:e.target.value})}/></label><label>A até venc.<input value={novo.plano_a_ate_vencimento} onChange={e=>setNovo({...novo,plano_a_ate_vencimento:e.target.value})}/></label><label>A após venc.<input value={novo.plano_a_apos_vencimento} onChange={e=>setNovo({...novo,plano_a_apos_vencimento:e.target.value})}/></label><label>Plano B parcelas<input type="number" value={novo.plano_b_parcelas} onChange={e=>setNovo({...novo,plano_b_parcelas:e.target.value})}/></label><label>B até venc.<input value={novo.plano_b_ate_vencimento} onChange={e=>setNovo({...novo,plano_b_ate_vencimento:e.target.value})}/></label><label>B após venc.<input value={novo.plano_b_apos_vencimento} onChange={e=>setNovo({...novo,plano_b_apos_vencimento:e.target.value})}/></label><label className="wide">Observação<input value={novo.observacao} onChange={e=>setNovo({...novo,observacao:e.target.value})}/></label></div><button className="primary addBtn" onClick={adicionar}><Plus size={16}/>Adicionar linha</button></div>
 </section>
}
