import { Fragment, useEffect, useMemo, useState } from 'react';
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { supabase } from './lib/supabase';
import { carregarCatalogoOficial, desativarProdutoOficial, fallbackCatalogo, upsertProdutoOficial } from './lib/comercialOficial';
import FechamentoGeral2027 from './FechamentoGeral2027';

const moeda=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const ORDEM_CATEGORIAS=['Mensalidade','Berçário','Tempo Integral','Fardamento','Material Didático','Material/Serviço','Alimentação','Day Care','Esportes','Taxa','Outros'];
const SERIES=['Berçário','Infantil I','Infantil II','Infantil III','Infantil IV','Infantil V','1º ano','2º ano','3º ano','4º ano','5º ano'];
const PERIODICIDADES=['mensal','único','avulso','diária','hora'];
const numero=v=>Number(String(v??'').replace(',','.'))||0;
const vazioNovo={categoria:'Mensalidade',produto:'',plano:'Plano A',valor2026:'',reajuste:'',valor2027:'',primeiraParcela2026:'',primeiraParcela2027:'',quantidadeParcelas:12,valorParcela2026:'',valorParcela2027:'',observacao:'',periodicidade:'mensal',obrigatorio:true,serieAplicavel:[]};

export default function ProdutosValores(){
 const [itens,setItens]=useState([]),[categoriaAtiva,setCategoriaAtiva]=useState('Todas'),[carregando,setCarregando]=useState(true),[salvando,setSalvando]=useState(false),[status,setStatus]=useState('Carregando tabela comercial...');
 const [novo,setNovo]=useState(vazioNovo);
 async function carregar(){setCarregando(true);try{const lista=await carregarCatalogoOficial();setItens(lista);setStatus('Tabela 2027 sincronizada com Supabase')}catch(e){setItens(fallbackCatalogo());setStatus(`Catálogo de contingência • ${e?.message||'tabela indisponível'}`)}finally{setCarregando(false)}}
 useEffect(()=>{carregar();const c=supabase.channel('produtos-oficiais-direcao').on('postgres_changes',{event:'*',schema:'public',table:'produtos_comerciais'},carregar).subscribe();return()=>supabase.removeChannel(c)},[]);
 const atualizar=(id,campo,valor)=>setItens(v=>v.map(i=>{if(i.id!==id)return i;const p={...i,[campo]:valor};if(campo==='reajuste'){const r=numero(valor);p.valor2027=Number((numero(i.valor2026)*(1+r/100)).toFixed(2));if(i.valorParcela2026!=='')p.valorParcela2027=Number((numero(i.valorParcela2026)*(1+r/100)).toFixed(2));if(i.primeiraParcela2026!=='')p.primeiraParcela2027=Number((numero(i.primeiraParcela2026)*(1+r/100)).toFixed(2))}return p}));
 const toggleSerie=(id,s)=>setItens(v=>v.map(i=>i.id===id?{...i,serieAplicavel:(i.serieAplicavel||[]).includes(s)?i.serieAplicavel.filter(x=>x!==s):[...(i.serieAplicavel||[]),s]}:i));
 const toggleSerieNovo=s=>setNovo(n=>({...n,serieAplicavel:n.serieAplicavel.includes(s)?n.serieAplicavel.filter(x=>x!==s):[...n.serieAplicavel,s]}));
 async function salvarTudo(){setSalvando(true);setStatus('Salvando...');try{await Promise.all(itens.map(upsertProdutoOficial));setStatus('Salvo • Atendimento e relatórios usarão os novos valores');await carregar()}catch(e){setStatus(`Erro: ${e.message}`)}finally{setSalvando(false)}}
 async function adicionar(){if(!novo.produto.trim())return;const r=numero(novo.reajuste),v26=numero(novo.valor2026),vp26=numero(novo.valorParcela2026||novo.valor2026);const item={...novo,id:`p-${Date.now()}`,produto:novo.produto.trim(),valor2026:v26,valor2027:novo.valor2027!==''?numero(novo.valor2027):Number((v26*(1+r/100)).toFixed(2)),valorParcela2026:vp26,valorParcela2027:novo.valorParcela2027!==''?numero(novo.valorParcela2027):Number((vp26*(1+r/100)).toFixed(2)),primeiraParcela2026:novo.primeiraParcela2026===''?'':numero(novo.primeiraParcela2026),primeiraParcela2027:novo.primeiraParcela2027!==''?numero(novo.primeiraParcela2027):(novo.primeiraParcela2026===''?'':Number((numero(novo.primeiraParcela2026)*(1+r/100)).toFixed(2))),ativo:true,turmaAplicavel:[]};try{await upsertProdutoOficial(item);setNovo(vazioNovo);setStatus('Novo plano/produto adicionado.');await carregar()}catch(e){setStatus(`Erro: ${e.message}`)}}
 async function excluir(id){if(!confirm('Desativar este item? O histórico será preservado.'))return;await desativarProdutoOficial(id);await carregar()}
 const categorias=useMemo(()=>[...new Set(itens.map(i=>i.categoria||'Outros'))].sort((a,b)=>(ORDEM_CATEGORIAS.indexOf(a)<0?999:ORDEM_CATEGORIAS.indexOf(a))-(ORDEM_CATEGORIAS.indexOf(b)<0?999:ORDEM_CATEGORIAS.indexOf(b))),[itens]);
 const visiveis=useMemo(()=>categoriaAtiva==='Todas'?itens:itens.filter(i=>i.categoria===categoriaAtiva),[itens,categoriaAtiva]);
 const grupos=useMemo(()=>categorias.map(c=>({categoria:c,itens:visiveis.filter(i=>i.categoria===c)})).filter(g=>g.itens.length),[categorias,visiveis]);
 const media=itens.length?itens.reduce((s,i)=>s+numero(i.reajuste),0)/itens.length:0;
 const inp=(i,c,w=92)=><input style={{width:w}} inputMode="decimal" type="text" value={i[c]??''} onChange={e=>atualizar(i.id,c,e.target.value)}/>;

 return <div className="comercialPage">
  <FechamentoGeral2027/>
  <section className="commercialSummary"><article><small>Itens oficiais</small><strong>{carregando?'...':itens.length}</strong></article><article><small>Reajuste médio</small><strong>{media.toFixed(2)}%</strong></article><article><small>Ano-base</small><strong>2026</strong></article><article><small>Tabela projetada</small><strong>2027</strong></article></section>
  <section className="panel categoryPanel"><div className="panelHead"><div><h3>Demais produtos e serviços 2027</h3><p>Fardamento, integral, alimentação, esportes e outros itens permanecem no catálogo oficial.</p></div><div style={{display:'flex',gap:8}}><button onClick={carregar}><RefreshCw size={16}/> Atualizar</button><button className="primary" onClick={salvarTudo} disabled={salvando}><Save size={16}/>{salvando?'Salvando...':'Salvar tabela'}</button></div></div><p style={{margin:'8px 0 14px'}}>{status}</p><div className="categoryTabs">{['Todas',...categorias].map(c=><button key={c} className={categoriaAtiva===c?'categoryTab active':'categoryTab'} onClick={()=>setCategoriaAtiva(c)}><span>{c}</span><b>{c==='Todas'?itens.length:itens.filter(i=>i.categoria===c).length}</b></button>)}</div></section>
  <section className="panel commercialTable"><div className="panelHead"><div><h3>Catálogo complementar</h3><p>Use esta tabela para produtos e serviços fora do Fechamento Geral de mensalidades.</p></div></div><div className="tableWrap"><table><thead><tr><th>Produto / séries</th><th>Plano</th><th>Valor 2026</th><th>Reajuste %</th><th>Valor 2027</th><th>1ª parc. 2026</th><th>1ª parc. 2027</th><th>Parcelas</th><th>Parcela 2026</th><th>Parcela 2027</th><th>Periodicidade</th><th>Obs.</th><th></th></tr></thead><tbody>{grupos.map(g=><Fragment key={g.categoria}><tr className="categoryDivider"><td colSpan="13"><div><strong>{g.categoria}</strong><span>{g.itens.length} item(ns)</span></div></td></tr>{g.itens.map(i=><tr key={i.id}><td style={{minWidth:230}}><input style={{width:'100%',fontWeight:700}} value={i.produto} onChange={e=>atualizar(i.id,'produto',e.target.value)}/><details><summary style={{cursor:'pointer',fontSize:11,marginTop:6}}>Séries ({(i.serieAplicavel||[]).length})</summary><div style={{display:'flex',flexWrap:'wrap',gap:5,maxWidth:360}}>{SERIES.map(s=><label key={s} style={{fontSize:10,display:'flex',gap:3}}><input type="checkbox" checked={(i.serieAplicavel||[]).includes(s)} onChange={()=>toggleSerie(i.id,s)}/>{s}</label>)}</div></details></td><td><input style={{width:82}} value={i.plano||''} onChange={e=>atualizar(i.id,'plano',e.target.value)} placeholder="Plano"/></td><td>{inp(i,'valor2026')}</td><td>{inp(i,'reajuste',70)}</td><td>{inp(i,'valor2027')}</td><td>{inp(i,'primeiraParcela2026')}</td><td>{inp(i,'primeiraParcela2027')}</td><td><input style={{width:62}} type="number" min="0" value={i.quantidadeParcelas??''} onChange={e=>atualizar(i.id,'quantidadeParcelas',e.target.value)}/></td><td>{inp(i,'valorParcela2026')}</td><td>{inp(i,'valorParcela2027')}</td><td><select value={i.periodicidade||'avulso'} onChange={e=>atualizar(i.id,'periodicidade',e.target.value)}>{PERIODICIDADES.map(p=><option key={p}>{p}</option>)}</select></td><td><input style={{minWidth:150}} value={i.observacao||''} onChange={e=>atualizar(i.id,'observacao',e.target.value)}/></td><td><button className="dangerIcon" onClick={()=>excluir(i.id)}><Trash2 size={16}/></button></td></tr>)}</Fragment>)}</tbody></table></div></section>
  <section className="panel addProduct"><div className="panelHead"><div><h3>Adicionar produto ou serviço</h3><p>Itens complementares ao fechamento geral.</p></div></div><div className="formGrid"><label>Produto / descrição<input value={novo.produto} onChange={e=>setNovo({...novo,produto:e.target.value})}/></label><label>Categoria<select value={novo.categoria} onChange={e=>setNovo({...novo,categoria:e.target.value})}>{ORDEM_CATEGORIAS.map(c=><option key={c}>{c}</option>)}</select></label><label>Plano<input value={novo.plano} onChange={e=>setNovo({...novo,plano:e.target.value})}/></label><label>Valor 2026<input value={novo.valor2026} onChange={e=>setNovo({...novo,valor2026:e.target.value})}/></label><label>Reajuste %<input value={novo.reajuste} onChange={e=>setNovo({...novo,reajuste:e.target.value})}/></label><label>Valor 2027<input value={novo.valor2027} onChange={e=>setNovo({...novo,valor2027:e.target.value})}/></label><label>Periodicidade<select value={novo.periodicidade} onChange={e=>setNovo({...novo,periodicidade:e.target.value})}>{PERIODICIDADES.map(p=><option key={p}>{p}</option>)}</select></label><label className="wide">Séries aplicáveis<div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:7}}>{SERIES.map(s=><label key={s} style={{display:'flex',gap:4,alignItems:'center'}}><input type="checkbox" checked={novo.serieAplicavel.includes(s)} onChange={()=>toggleSerieNovo(s)}/>{s}</label>)}</div></label><label className="wide">Observação<input value={novo.observacao} onChange={e=>setNovo({...novo,observacao:e.target.value)}/></label></div><button className="primary addBtn" onClick={adicionar}><Plus size={17}/>Adicionar produto</button></section>
 </div>
}
